-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 15:51:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Consultas` (
  `idConsultas` VARCHAR(45) NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  `valor` DECIMAL(5,2) NULL,
  `Busca_especialidade` VARCHAR(45) NULL,
  `Medico_idMedico` INT NOT NULL,
  `Convenio_idConvenio` INT NOT NULL,
  PRIMARY KEY (`idConsultas`),
  CONSTRAINT `fk_Consultas_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultas_Convenio1`
    FOREIGN KEY (`Convenio_idConvenio`)
    REFERENCES `Convenio` (`idConvenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Consultas_Medico1_idx` ON `Consultas` (`Medico_idMedico` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Consultas_Convenio1_idx` ON `Consultas` (`Convenio_idConvenio` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Convenio` (
  `idConvenio` INT NOT NULL,
  `cpnj` CHAR(12) NULL,
  `nome` VARCHAR(45) NULL,
  `carencia` DATE NULL,
  `carteira` VARCHAR(45) NULL,
  PRIMARY KEY (`idConvenio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Endereço` (
  `idEndereço` INT NOT NULL,
  `cep` INT(8) NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`idEndereço`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Enfermeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enfermeiro` (
  `idtable4` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` CHAR(12) NULL,
  `cre` CHAR(12) NULL,
  `Endereço_idEndereço` INT NOT NULL,
  `telefone_idtelefone` INT NOT NULL,
  PRIMARY KEY (`idtable4`),
  CONSTRAINT `fk_Enfermeiro_Endereço1`
    FOREIGN KEY (`Endereço_idEndereço`)
    REFERENCES `Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfermeiro_telefone1`
    FOREIGN KEY (`telefone_idtelefone`)
    REFERENCES `telefone` (`idtelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Enfermeiro_Endereço1_idx` ON `Enfermeiro` (`Endereço_idEndereço` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Enfermeiro_telefone1_idx` ON `Enfermeiro` (`telefone_idtelefone` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Internação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Internação` (
  `idInternação` INT NOT NULL,
  `data_entrada` DATE NULL,
  `data_prev_alta` DATE NULL,
  `data_alta` DATE NULL,
  `procedimento` VARCHAR(45) NULL,
  `Quarto_idQuarto` INT NOT NULL,
  PRIMARY KEY (`idInternação`),
  CONSTRAINT `fk_Internação_Quarto1`
    FOREIGN KEY (`Quarto_idQuarto`)
    REFERENCES `Quarto` (`idQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Internação_Quarto1_idx` ON `Internação` (`Quarto_idQuarto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Medico` (
  `idMedico` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` CHAR(12) NULL,
  `cre` CHAR(12) NULL,
  `cargo` VARCHAR(45) NULL,
  `especialidades` VARCHAR(45) NULL,
  `Endereço_idEndereço` INT NOT NULL,
  `telefone_idtelefone` INT NOT NULL,
  PRIMARY KEY (`idMedico`),
  CONSTRAINT `fk_Medico_Endereço1`
    FOREIGN KEY (`Endereço_idEndereço`)
    REFERENCES `Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_telefone1`
    FOREIGN KEY (`telefone_idtelefone`)
    REFERENCES `telefone` (`idtelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Medico_Endereço1_idx` ON `Medico` (`Endereço_idEndereço` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Medico_telefone1_idx` ON `Medico` (`telefone_idtelefone` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paciente` (
  `idPaciente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `email` VARCHAR(45) NULL,
  `cpf` CHAR(12) NULL,
  `rg` CHAR(12) NULL,
  `Endereço_idEndereço` INT NOT NULL,
  `telefone_idtelefone` INT NOT NULL,
  `Quarto_idQuarto` INT NOT NULL,
  `Consultas_idConsultas` VARCHAR(45) NOT NULL,
  `Convenio_idConvenio` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  CONSTRAINT `fk_Paciente_Endereço`
    FOREIGN KEY (`Endereço_idEndereço`)
    REFERENCES `Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_telefone1`
    FOREIGN KEY (`telefone_idtelefone`)
    REFERENCES `telefone` (`idtelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Quarto1`
    FOREIGN KEY (`Quarto_idQuarto`)
    REFERENCES `Quarto` (`idQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Consultas1`
    FOREIGN KEY (`Consultas_idConsultas`)
    REFERENCES `Consultas` (`idConsultas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Convenio1`
    FOREIGN KEY (`Convenio_idConvenio`)
    REFERENCES `Convenio` (`idConvenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Paciente_Endereço_idx` ON `Paciente` (`Endereço_idEndereço` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Paciente_telefone1_idx` ON `Paciente` (`telefone_idtelefone` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Paciente_Quarto1_idx` ON `Paciente` (`Quarto_idQuarto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Paciente_Consultas1_idx` ON `Paciente` (`Consultas_idConsultas` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Paciente_Convenio1_idx` ON `Paciente` (`Convenio_idConvenio` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Paciente_has_Internação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paciente_has_Internação` (
  `Paciente_idPaciente` INT NOT NULL,
  `Paciente_Convenio_idConvenio` INT NOT NULL,
  `Internação_idInternação` INT NOT NULL,
  PRIMARY KEY (`Paciente_idPaciente`, `Paciente_Convenio_idConvenio`, `Internação_idInternação`),
  CONSTRAINT `fk_Paciente_has_Internação_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Internação_Internação1`
    FOREIGN KEY (`Internação_idInternação`)
    REFERENCES `Internação` (`idInternação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Paciente_has_Internação_Internação1_idx` ON `Paciente_has_Internação` (`Internação_idInternação` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Paciente_has_Internação_Paciente1_idx` ON `Paciente_has_Internação` (`Paciente_idPaciente` ASC, `Paciente_Convenio_idConvenio` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quarto` (
  `idQuarto` INT NOT NULL,
  `numero` INT(20) NULL,
  `tipo` VARCHAR(45) NULL,
  `Tipo Quarto_idTipo Quarto` INT NOT NULL,
  `Enfermeiro_idtable4` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idQuarto`),
  CONSTRAINT `fk_Quarto_Tipo Quarto1`
    FOREIGN KEY (`Tipo Quarto_idTipo Quarto`)
    REFERENCES `Tipo Quarto` (`idTipo Quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quarto_Enfermeiro1`
    FOREIGN KEY (`Enfermeiro_idtable4`)
    REFERENCES `Enfermeiro` (`idtable4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quarto_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Quarto_Tipo Quarto1_idx` ON `Quarto` (`Tipo Quarto_idTipo Quarto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Quarto_Enfermeiro1_idx` ON `Quarto` (`Enfermeiro_idtable4` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Quarto_Medico1_idx` ON `Quarto` (`Medico_idMedico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Receita` (
  `idReceita` VARCHAR(45) NOT NULL,
  `encerramento_consulta` TIME NULL,
  `medicamentos` VARCHAR(45) NULL,
  `quantidade` INT(20) NULL,
  `instruções` VARCHAR(45) NULL,
  `Consultas_idConsultas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReceita`),
  CONSTRAINT `fk_Receita_Consultas1`
    FOREIGN KEY (`Consultas_idConsultas`)
    REFERENCES `Consultas` (`idConsultas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Receita_Consultas1_idx` ON `Receita` (`Consultas_idConsultas` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tipo Quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tipo Quarto` (
  `idTipo Quarto` INT NOT NULL,
  `descrição` VARCHAR(45) NULL,
  `valor_diaria` DECIMAL(5,2) NULL,
  PRIMARY KEY (`idTipo Quarto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `especialidade` (
  `idespecialidade` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idespecialidade`),
  CONSTRAINT `fk_especialidade_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_especialidade_Medico1_idx` ON `especialidade` (`Medico_idMedico` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telefone` (
  `idtelefone` INT NOT NULL,
  `ddd` INT(2) NULL,
  `telefone` INT(9) NULL,
  PRIMARY KEY (`idtelefone`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
